SCREEN_SIZE = width, height = 1600, 800

BIRD_NUMBER = 50
PREDATOR_NUMBER = 3

BIRD_COLLISION_RANGE = 40
BIRD_DETECTION_RANGE = 80
BIRD_VISIONANGLE = 90.0

PREDATOR_COLLISION_RANGE = 40
PREDATOR_DETECTION_RANGE = 200
PREDATOR_VISION_ANGLE = 45.0

AVOID_WEIGHT = 0.02
MEAN_SPEED_WEIGHT = 1.0
MEAN_POS_WEIGHT = 1.0
FLEE_WEIGHT = 2.0
CHASE_WEIGHT = 2.0

BIRD_MAX_SPEED = 0.2
BIRD_MAX_TURN_ANGLE = 0.03
